language: node_js
cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - '10'

install: npm ci


jobs:
  include:
    - stage: test
      script: npx run clean test build
    - stage: publish
      if: branch = master
      script: npx run cd
